    "code"    :"gfdggfgd",
    "type_achat"      :"gfdggfgd",
    "_achat"    :"gfdggfgd",
    "mode_paiement" :"gfdggfgd", 
    "montant_total_ht"  :"gfdggfgd",
    "montant_total_ttc"    :"gfdggfgd",
    "montant_total_tva"   :"gfdggfgd",
    "net_a_payer_ht"   :"gfdggfgd",
    "remise" :"gfdggfgd",
    "net_a_payer"    :"gfdggfgd",
    "longitude_livraison" :"gfdggfgd",
    "latitude_livraison" :"gfdggfgd",
    "adresse_livraison"    :"gfdggfgd",
    "_prevu_livraison"    :"gfdggfgd",
    "commentaire":"gfdggfgd",
    "annule" :"gfdggfgd",

    "user_code"     :"11215134917",
    "grossiste_code" :"gfdggfgd",
    "fournisseur_code" : "gdfgdfgdfgdf"